#!/usr/bin/env bash
# protect-files.sh — Block writes to sensitive files, ask for confirmation on config files.
# Exit 0 = allow, exit 2 = block
# Prints "ask" to stdout to trigger confirmation prompt.

set -euo pipefail

# Extract the file path from the tool input.
# Claude Code passes tool input as JSON on stdin.
if command -v jq &>/dev/null; then
  FILE_PATH=$(cat /dev/stdin | jq -r '.file_path // empty')
else
  # Fallback: naive extraction without jq
  FILE_PATH=$(cat /dev/stdin | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# If we couldn't extract a file path, allow the operation
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Get just the filename and relative path for pattern matching
BASENAME=$(basename "$FILE_PATH")
REL_PATH="$FILE_PATH"

# BLOCK: Sensitive files that should never be written by Claude
case "$BASENAME" in
  .env|.env.*|.env.local)
    echo "BLOCKED: Writing to environment file '$BASENAME' is not allowed."
    exit 2
    ;;
  *.pem|*.key)
    echo "BLOCKED: Writing to certificate/key file '$BASENAME' is not allowed."
    exit 2
    ;;
  *credentials*)
    echo "BLOCKED: Writing to credentials file '$BASENAME' is not allowed."
    exit 2
    ;;
esac

# BLOCK: Sensitive directories
case "$REL_PATH" in
  secrets/*|*/secrets/*)
    echo "BLOCKED: Writing to secrets/ directory is not allowed."
    exit 2
    ;;
  .git/*|*/.git/*)
    echo "BLOCKED: Writing to .git/ directory is not allowed."
    exit 2
    ;;
  dist/*|*/dist/*)
    echo "BLOCKED: Writing to dist/ directory is not allowed. Build output is auto-generated."
    exit 2
    ;;
esac

# BLOCK: Lock files (should be auto-generated by package manager)
case "$BASENAME" in
  pnpm-lock.yaml|package-lock.json|yarn.lock)
    echo "BLOCKED: Writing to '$BASENAME' is not allowed. Lock files are auto-generated."
    exit 2
    ;;
esac

# ASK: Config files that need careful review
case "$REL_PATH" in
  .claude/settings.local.json|*/.claude/settings.local.json)
    echo "ask"
    echo "This modifies Claude Code settings. Please confirm this is intentional."
    exit 0
    ;;
esac

case "$BASENAME" in
  CLAUDE.md)
    echo "ask"
    echo "This modifies CLAUDE.md project instructions. Please confirm this is intentional."
    exit 0
    ;;
esac

# ALLOW: Everything else
exit 0
