"""mcpspec — convenience wrapper for mcpspec-dev.

Install: pip install mcpspec
Import: from mcpspec import McpSpec
"""

from mcpspec_dev import (
    IntrospectionError,
    IntrospectionPrompt,
    IntrospectionPromptArgument,
    IntrospectionResource,
    IntrospectionResult,
    IntrospectionTool,
    McpSpec,
    McpSpecAuth,
    McpSpecAuthor,
    McpSpecDocument,
    McpSpecError,
    McpSpecInfo,
    McpSpecOptions,
    McpSpecPrompt,
    McpSpecPromptArgument,
    McpSpecResource,
    McpSpecTool,
    McpSpecToolAnnotations,
    McpSpecToolExample,
    McpSpecTransport,
    PromptOverride,
    ResourceOverride,
    SpecGenerationError,
    ToolOverride,
    create_docs_route,
    create_yaml_route,
    filter_items,
    generate_spec,
    introspect,
    match_glob,
    serialize_spec,
)

__all__ = [
    "IntrospectionError",
    "IntrospectionPrompt",
    "IntrospectionPromptArgument",
    "IntrospectionResource",
    "IntrospectionResult",
    "IntrospectionTool",
    "McpSpec",
    "McpSpecAuth",
    "McpSpecAuthor",
    "McpSpecDocument",
    "McpSpecError",
    "McpSpecInfo",
    "McpSpecOptions",
    "McpSpecPrompt",
    "McpSpecPromptArgument",
    "McpSpecResource",
    "McpSpecTool",
    "McpSpecToolAnnotations",
    "McpSpecToolExample",
    "McpSpecTransport",
    "PromptOverride",
    "ResourceOverride",
    "SpecGenerationError",
    "ToolOverride",
    "create_docs_route",
    "create_yaml_route",
    "filter_items",
    "generate_spec",
    "introspect",
    "match_glob",
    "serialize_spec",
]
