import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const docsHtmlPath = join(root, "packages/typescript/src/ui/docs.html");

if (!existsSync(docsHtmlPath)) {
  console.error("docs.html not found. Run 'pnpm build' first to generate it.");
  process.exit(1);
}

const docsHtml = readFileSync(docsHtmlPath, "utf-8");

// Escape backticks and ${} for template literal embedding
const escaped = docsHtml
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const output = `// Generated by scripts/build-website.js — do not edit manually\n// Source: docs-ui/ (built into packages/typescript/src/ui/docs.html)\nvar DOCS_TEMPLATE = \`${escaped}\`;\n`;

writeFileSync(join(root, "website/docs-template.js"), output, "utf-8");
console.log("Built website/docs-template.js (" + Buffer.byteLength(output, "utf-8") + " bytes)");
